@startuml
'https://plantuml.com/class-diagram

class Controller
{
    -DatePicker itemDueDate
    -TextField itemName
    -CheckBox itemComplete
    -TextArea itemDescription
    -ComboBox<String> listFilter
    -TextField listName
    -ListView<ToDoListItem> toDoItems
    -ListView<ToDoList> toDoLists
    -AnchorPane listInspector
    -AnchorPane toDoInspector
    -AnchorPane toDoPane
    -Group toDoButtons
    -ToDoList currentlySelected
    -ToDoListItem currentlySelectedItem
    -int listSize
    -int itemListSize

    +initialize(URL url, ResourceBundle rb)
    +addToDoListItem()
    -ResetItemInspector()
    +createNewList()
    -onSelectionChanged()
    -onItemSelectionChanged()
    +filterList()
    -makeIncompleteVisible()
    -makeCompletedVisible()
    -makeAllVisible()
    -CheckFilter()
    -CheckItemCount()
    +removeList()
    +removeToDoListItem()
    +clearToDoList()
    +saveToDoList()
    +openNewListsFromFile()
    -String putListDataIntoString()
    -ToDoList putStringIntoNewList(File data)
}

@enduml