@startuml
'https://plantuml.com/class-diagram

class ToDoList
{
    +ListView<ToDoListItem> hiddenItems
    +TextField listName
    +ComboBox<String> listFilter
    +ObservableList<ToDoListItem> observableListItems

    +String ToString()
    -ToDoList()
}

@enduml